export default () => ({
  nodeEnv: process.env.NODE_ENV || 'development',
  logLevel: process.env.LOG_LEVEL || 'log',
  api: {
    port: parseInt(process.env.API_PORT || '4000', 10),
    baseUrl: process.env.API_BASE_URL || 'http://localhost:4000',
  },
  corsOrigins: (process.env.CORS_ORIGINS || '').split(',').filter(Boolean),
  database: { url: process.env.DATABASE_URL },
  redis: {
    url: process.env.REDIS_URL || '',
    host: process.env.REDIS_HOST || 'redis',
    port: parseInt(process.env.REDIS_PORT || '6379', 10),
    password: process.env.REDIS_PASSWORD || '',
  },
  jwt: {
    secret: process.env.JWT_SECRET || 'dev-insecure-secret-change-me',
    accessTtl: process.env.JWT_ACCESS_TTL || '15m',
    refreshTtl: process.env.JWT_REFRESH_TTL || '30d',
  },
  auth: {
    google: { clientId: process.env.GOOGLE_CLIENT_ID, clientSecret: process.env.GOOGLE_CLIENT_SECRET },
    apple: {
      clientId: process.env.APPLE_CLIENT_ID,
      teamId: process.env.APPLE_TEAM_ID,
      keyId: process.env.APPLE_KEY_ID,
      privateKeyPath: process.env.APPLE_PRIVATE_KEY_PATH,
    },
    facebook: { appId: process.env.FACEBOOK_APP_ID, appSecret: process.env.FACEBOOK_APP_SECRET },
    bootstrapSuperAdminEmail: process.env.BOOTSTRAP_SUPER_ADMIN_EMAIL,
  },
  push: {
    expoAccessToken: process.env.EXPO_ACCESS_TOKEN,
    mode: (process.env.PUSH_MODE || 'expo') as 'expo' | 'relay' | 'none',
    relayUrl: process.env.PUSH_RELAY_URL,
    vapidPublicKey: process.env.VAPID_PUBLIC_KEY || '',
    vapidPrivateKey: process.env.VAPID_PRIVATE_KEY || '',
    vapidSubject: process.env.VAPID_SUBJECT || 'mailto:noreply@tvwatchtime.org',
  },
  metadata: {
    tmdbApiKey: process.env.TMDB_API_KEY,
    tmdbLanguage: process.env.TMDB_LANGUAGE || 'en-US',
    tmdbRps: Number(process.env.TMDB_RPS || 40),
    tvdbApiKey: process.env.TVDB_API_KEY,
    tvdbPin: process.env.TVDB_PIN,
    tvdbRps: Number(process.env.TVDB_RPS || 10),
    tvmazeEnabled: process.env.TVMAZE_ENABLED !== 'false',
    tvmazeApiKey: process.env.TVMAZE_API_KEY,
    useApiRatingsForChart: process.env.USE_API_FOR_EPISODES_CHART === 'true',
    trakt: {
      clientId: process.env.TRAKT_CLIENT_ID,
      clientSecret: process.env.TRAKT_CLIENT_SECRET,
    },
    pushMode: process.env.PUSH_MODE || 'expo',
    relayUrl: process.env.PUSH_RELAY_URL,
  },
  jobs: {
    metadataRefreshCron: process.env.METADATA_REFRESH_CRON || '0 3 * * *',
    notificationsDispatchCron: process.env.NOTIFICATIONS_DISPATCH_CRON || '*/5 * * * *',
  },
  imports: {
    dailyLimit: Number(process.env.IMPORT_DAILY_LIMIT || 3),
  },
  commentImages: {
    openaiApiKey: process.env.OPENAI_API_KEY,
    openaiModerationModel: process.env.OPENAI_MODERATION_MODEL || 'omni-moderation-latest',
    s3Region: process.env.S3_REGION || process.env.AWS_REGION || 'us-east-1',
    s3Bucket: process.env.S3_BUCKET_COMMENT_IMAGES || process.env.S3_BUCKET || 'tvwatch-comment-images',
    s3TempBucket: process.env.S3_BUCKET_TEMP_UPLOADS || 'tvwatch-temp-uploads',
    s3Endpoint: process.env.S3_ENDPOINT,
    s3AccessKeyId: process.env.S3_ACCESS_KEY_ID || process.env.AWS_ACCESS_KEY_ID,
    s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY || process.env.AWS_SECRET_ACCESS_KEY,
    encryptionMasterKey: process.env.ENCRYPTION_MASTER_KEY || 'dev-master-key-change-in-prod-32bytes!',
    maxUploadMb: Number(process.env.MAX_COMMENT_IMAGE_UPLOAD_MB || 5),
    maxHardLimitMb: Number(process.env.MAX_COMMENT_IMAGE_HARD_LIMIT_MB || 20),
    maxPixels: Number(process.env.MAX_COMMENT_IMAGE_PIXELS || 36000000),
    maxLongEdge: Number(process.env.COMMENT_IMAGE_MAX_LONG_EDGE || 1600),
    webpQuality: Number(process.env.COMMENT_IMAGE_WEBP_QUALITY || 95),
    thumbMaxLongEdge: Number(process.env.COMMENT_THUMBNAIL_MAX_LONG_EDGE || 480),
    thumbWebpQuality: Number(process.env.COMMENT_THUMBNAIL_WEBP_QUALITY || 85),
    uploadsPerUserPerDay: Number(process.env.COMMENT_IMAGE_UPLOADS_PER_USER_PER_DAY || 20),
    workerConcurrency: Number(process.env.COMMENT_IMAGE_WORKER_CONCURRENCY || 2),
  },
  notifications: {
    maxPushPerUserPerDay: Number(process.env.MAX_PUSH_NOTIFICATIONS_PER_USER_PER_DAY || 3),
    spreadStartHour: Number(process.env.NOTIFICATION_SPREAD_START_HOUR || 12),
  },
  pushRelay: {
    rateLimit: Number(process.env.PUSH_RELAY_RATE_LIMIT || 10),
    rateWindowMinutes: Number(process.env.PUSH_RELAY_RATE_WINDOW_MINUTES || 10),
    enabled: process.env.PUSH_RELAY_ENABLED !== 'false',
  },
  email: {
    enabled: !!(process.env.SMTP_HOST),
    host: process.env.SMTP_HOST || '',
    port: Number(process.env.SMTP_PORT || 587),
    secure: process.env.SMTP_SECURE === 'true',
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASSWORD || '',
    from: process.env.SMTP_FROM || 'no-reply@tvwatchtime.org',
  },
  site: {
    url: process.env.SITE_URL || 'https://tvwatchtime.org',
  },
  storage: {
    s3PublicBaseUrl: process.env.S3_PUBLIC_BASE_URL || '',
  },
  // ---- Multi-provider resilience (flat keys so SettingService/env precedence works) ----
  TVDB_ENABLED: process.env.TVDB_ENABLED !== 'false',
  TVDB_PIN: process.env.TVDB_PIN,
  TVDB_REQUESTS_PER_SECOND: Number(process.env.TVDB_REQUESTS_PER_SECOND || 2),
  TVDB_REQUESTS_PER_MINUTE: Number(process.env.TVDB_REQUESTS_PER_MINUTE || 60),
  TVDB_CONCURRENCY: Number(process.env.TVDB_CONCURRENCY || 2),
  TVDB_TIMEOUT_MS: Number(process.env.TVDB_TIMEOUT_MS || 10000),
  TVDB_MAX_RETRIES: Number(process.env.TVDB_MAX_RETRIES || 5),
  TVDB_BACKOFF_BASE_MS: Number(process.env.TVDB_BACKOFF_BASE_MS || 500),
  TVDB_BACKOFF_MAX_MS: Number(process.env.TVDB_BACKOFF_MAX_MS || 30000),
  TVDB_CACHE_TTL_SECONDS: Number(process.env.TVDB_CACHE_TTL_SECONDS || 86400),
  TVDB_NEGATIVE_CACHE_TTL_SECONDS: Number(process.env.TVDB_NEGATIVE_CACHE_TTL_SECONDS || 3600),
  KITSU_ENABLED: process.env.KITSU_ENABLED !== 'false',
  KITSU_BASE_URL: process.env.KITSU_BASE_URL || 'https://kitsu.app/api/edge',
  KITSU_API_MODE: process.env.KITSU_API_MODE || 'jsonapi',
  KITSU_REQUESTS_PER_SECOND: Number(process.env.KITSU_REQUESTS_PER_SECOND || 3),
  KITSU_REQUESTS_PER_MINUTE: Number(process.env.KITSU_REQUESTS_PER_MINUTE || 60),
  KITSU_CONCURRENCY: Number(process.env.KITSU_CONCURRENCY || 2),
  KITSU_TIMEOUT_MS: Number(process.env.KITSU_TIMEOUT_MS || 10000),
  KITSU_MAX_RETRIES: Number(process.env.KITSU_MAX_RETRIES || 5),
  KITSU_BACKOFF_BASE_MS: Number(process.env.KITSU_BACKOFF_BASE_MS || 500),
  KITSU_BACKOFF_MAX_MS: Number(process.env.KITSU_BACKOFF_MAX_MS || 30000),
  KITSU_CACHE_TTL_SECONDS: Number(process.env.KITSU_CACHE_TTL_SECONDS || 86400),
  JIKAN_ENABLED: process.env.JIKAN_ENABLED !== 'false',
  JIKAN_BASE_URL: process.env.JIKAN_BASE_URL || 'https://api.jikan.moe/v4',
  JIKAN_PUBLIC_FALLBACK: process.env.JIKAN_PUBLIC_FALLBACK !== 'false',
  JIKAN_REQUESTS_PER_SECOND: Number(process.env.JIKAN_REQUESTS_PER_SECOND || 3),
  JIKAN_REQUESTS_PER_MINUTE: Number(process.env.JIKAN_REQUESTS_PER_MINUTE || 60),
  JIKAN_CONCURRENCY: Number(process.env.JIKAN_CONCURRENCY || 2),
  JIKAN_TIMEOUT_MS: Number(process.env.JIKAN_TIMEOUT_MS || 15000),
  JIKAN_MAX_RETRIES: Number(process.env.JIKAN_MAX_RETRIES || 5),
  JIKAN_BACKOFF_BASE_MS: Number(process.env.JIKAN_BACKOFF_BASE_MS || 750),
  JIKAN_BACKOFF_MAX_MS: Number(process.env.JIKAN_BACKOFF_MAX_MS || 60000),
  JIKAN_CACHE_TTL_SECONDS: Number(process.env.JIKAN_CACHE_TTL_SECONDS || 86400),
});
