ALTER TYPE "ListSource" ADD VALUE IF NOT EXISTS 'PLEX';
ALTER TYPE "ListSource" ADD VALUE IF NOT EXISTS 'EMBY';

ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'PLEX';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'EMBY';
